### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by phated** [gulpjs/evented-require#1]
@sttk can you review this implementation please.  I'm trying to refactor some things out of Liftoff (I have some ideas on how to integrate this with my new changes).

**Comment by sttk** [comment]
@phated I've reviewed and there are some confirmations and suggestions:

1. I think it's better to add a comment of [the purpose](https://github.com/gulpjs/evented-require/blob/master/test/index.test.js#L152) of [L16-L17](https://github.com/gulpjs/evented-require/blob/master/index.js#L16-L17).
2. Is it appropriate for us that the default `basedir` is [this](https://github.com/browserify/resolve/blob/master/lib/sync.js#L39)?
3. Is it better these event name can have an user specified prefix? For example:

    ```js
    const loader = new EventedRequire(basedir, { eventPrefix: 'preload:' });
    loader.on('preload:before', (moduleName, result) => { ... });
    loader.on('preload:success', (moduleName, result) => { ... });
    loader.on('preload:failure', (moduleName, result) => { ... });
    ```

4. nyc and coveralls should be upgraded because a lot of warning and vulnerabilities are printed when `npm install`. I think it is enough to measure coverage only newer versions (>=node.js v6).

**Comment by phated** [comment]
Thanks for reviewing!

1. I'll add a comment.  I should also add a test for the `requireAll` destructuring
2. The `resolve` module already does that defaulting so we shouldn't have to.
3. I am planning to make another module that re-emits events and maps them to different names so I don't think we need namespaces/prefix
4. I like when the whole suite is run against the entire matrix and the warnings only show up when you `npm install` inside the module itself, not when someone installs it into their project. Once we actually begin work on gulp 5, we'll be able to drop support for all of the old stuff.
